config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :index, :show]
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :creator, class_name: 'User'
	has_many :attendees, through: :event_attendences
	has_many :event_attendences

	scope :prev, -> { where(:date => date.past?) }
	scope :next, -> { where(:date => date.future?) }
end

app/models/event_attendence.rb
class EventAttendence < ActiveRecord::Base
	belongs_to :event_attendence, class_name: 'Event'
	belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events, :foreign_key => :creator_id 
	has_many :attended_event, through: :event_attendences, source: :event_attendence
	has_many :event_attendences

	# def prev_events
	# 	self.events.each do |event|
	# 		if event.date.past?
	# 			p event 
	# 		end
	# 	end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :require_login, only: [:new, :create]

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			redirect_to @event
		else
			flash[:danger] = failure
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	private

		def event_params
			params.require(:event).permit(:name, :description, :date, :time)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(name: params[:session][:name].downcase)
		if user
			log_in(user)
			redirect_to user
		else
			flash[:danger] = 'Name not found'
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, only: [:show]

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			redirect_to @user
		else
			flash.now[:danger] = 'Sign up failure'
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])

		if params[:prev]
   		@events = current_user.events.where('date <= ?', Date.today)
		else
			@events = current_user.events.where('date >= ?', Date.tomorrow)
		end

		
		# @prev_events = current_user.prev_events
	end

	private

		def user_params
			params.require(:user).permit(:name, :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session[:user_id] = nil
	end

	def require_login
			unless logged_in?
				flash[:info] = 'Must be logged in'
				redirect_to login_path
			end
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.slim
h3 Future Events
- @events.each do |event|
	p = event.name if event.date.future?


h3 Past Events
- @events.each do |event|
	p = event.name if event.date.past?

app/views/events/new.html.slim
h1.center Create event

.row
	.col-md-6.col-md-offset-3
		= form_for @event do |f|
			= f.label :name
			= f.text_field :name, class: 'form-control'

			= f.label :description
			= f.text_area :description, class: 'form-control', rows: 6

			
			= f.label :date
			= f.datetime_select :date, ampm: true, minute_step: 15


			= f.submit 'Create', class: 'btn btn-primary btn-block'

app/views/events/show.html.slim
h2 = @event.name

p Host: #{ @event.creator.name }
p Description: #{ @event.description }
p Date: #{ @event.date }

h3 attendence (#{@event.event_attendences.count})
ul
	- @event.event_attendences.each do |attendee|
	 li = attendee

app/views/layouts/_header.html.slim
header.navbar.navbar-default.navbar-fixed-top
	div.container
		nav
			ul.nav.nav-pills.navbar-right
				li = link_to 'Events', events_path
				li = link_to 'Create event', new_event_path

				- if logged_in? 
					li = link_to 'Logout', logout_path, method: :delete
				- else
					li = link_to 'Login', login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Private Events
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
  	= render 'layouts/header'

  	div.container
  		- flash.each do |message_type, message|
  			div class="alert alert-#{ message_type }" = message
    	== yield

app/views/users/new.html.slim
h1.center Sign up

div.row
	div.col-md-4.col-md-offset-4
		= form_for @user do |f|
			= f.label :name
			= f.text_field :name, class: 'form-control'

			= f.label :email
			= f.email_field :email, class: 'form-control'

			= f.submit 'Create account', class: 'btn btn-primary'

app/views/users/show.html.slim
p = @user.name
p = @user.email


form action=user_path
	input type='submit' name='prev' value='Prev' class='btn btn-primary'
	input type='submit' name='next' value='Next' class='btn btn-primary'

h1 Events
- @events.each do |event|
	p = event.name






/ ul 
/ 	- @prev_events.each do |event|
/ 		li = p event.name
		
/ 		<hr />